### ISSUE TITLE
How can I send RAW POST data?

### ISSUE THREAD

**Issue by wislem** [codezero-be/courier#2]
Using this:

``` php
$response = $courier->post($endpoint, $parameters, $headers);
```

allows only array for the $parameters variable.

**Comment by ivanvermeyen** [comment]
Hi,

What do you mean by RAW post data?

`$parameters` is an array of data that is sent with the request.

If you submitted a form and you want to use its data to send a request, you could do something like this:

```
$parameters['myKey'] = $_POST['myKey'];
```

If you have a query string like `myKey=something&myOtherKey=somethingElse`, then you could convert that into an array using `parse_str()` as described here:

http://stackoverflow.com/questions/3951454/is-there-a-php-function-to-convert-a-query-string-to-an-array

And then build up your `$parameters` array.

Hope this helps... If I misunderstood your question, could you describe it a bit more?

**Comment by wislem** [comment]
Check here.
http://stackoverflow.com/questions/871431/raw-post-using-curl-in-php

There is an option to POST a string using Curl, not just an array.

Thanks for answering so fast btw :)

**Comment by ivanvermeyen** [comment]
I see! I'm afraid I didn't implement this...

If you don't mind setting some CURL options manually, mabye take a look at my core cURL wrapper: https://github.com/codezero-be/curl

You could also check out http://docs.guzzlephp.org/ which is a much more advanced and very popular package :)

Thanks for pointing this out, I will keep this in mind. Though I don't have the time to work on this package at the moment.

**Comment by wislem** [comment]
No problem Ivan :)

I think I'll go for Guzzle!

**Comment by ivanvermeyen** [comment]
:+1:
